# paths
model_name: bert-base-cased
model_dir: /Users/tadeuskostusko/Desktop/sci_checked_bot/models/model
tokenizer_dir: /Users/tadeuskostusko/Desktop/sci_checked_bot/models/tokenizer

# training params
learning_rate: 5e-5
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
num_train_epochs: 3
weight_decay: 0.01
output_dir: ../outputs/
eval_strategy: epoch
save_strategy: epoch
save_total_limit: 1
seed: 42
gradient_accumulation_steps: 1
